server:
  port: 8085
hbase:
  config:
    hbase.zookeeper.quorum: hadoop1,hadoop2,hadoop3
    hbase.zookeeper.property.clientPort: 2181
    hbase.master.port: 16000
    hbase.regionserver.port: 16201
    zookeeper.znode.parent: /hbase
    hbase.client.keyvalue.maxsize: 1048576000